version: "3.3"
services: 
  db: 
    image: mariadb:10.6.4-focal 
    command: '--default-authentication-plugin=mysql_native_password'
    volumes: 
      - ./wordpress/db_data:/var/lib/mysql
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD=123456 
      - MYSQL_DATABASE=d8wp 
      - MYSQL_USER=wp  
      - MYSQL_PASSWORD=123456 
    expose: 
      - 3306
      - 33060
  wordpress: 
    image: wordpress:latest 
    volumes:
      - ./wordpress/wp_data:/var/www/html
    ports: 
      - 80:80
    restart: always  
    environment: 
      - WORDPRESS_DB_HOST=db 
      - WORDPRESS_DB_USER=wp 
      - WORDPRESS_DB_PASSWORD=123456 
      - WORDPRESS_DB_NAME=d8wp 
